# Generated by Django 5.2.3 on 2026-02-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaint_category'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='complaints.complaint'),
        ),
    ]
