# Generated by Django 5.2.3 on 2026-02-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_hospital_response_and_complaint_lifecycle'),
        ('social', '0004_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='related_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('hospital', 'Hospital Admin'), ('authority', 'Health Authority'), ('superadmin', 'Super Admin')], max_length=20, null=True),
        ),
    ]
