# Generated by Django 5.2.3 on 2026-06-14 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('user_frozen', 'User Frozen'), ('user_unfrozen', 'User Unfrozen'), ('user_blocked', 'User Blocked'), ('user_unblocked', 'User Unblocked'), ('user_reactivated', 'User Reactivated'), ('user_warned', 'User Warned'), ('freeze_appeal_approved', 'Freeze Appeal Approved'), ('freeze_appeal_rejected', 'Freeze Appeal Rejected'), ('category_added', 'Category Added'), ('category_deleted', 'Category Deleted'), ('support_ticket_replied', 'Support Ticket Replied'), ('settings_changed', 'Settings Changed'), ('password_changed', 'Password Changed'), ('account_deactivated', 'Account Deactivated')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action taken')),
                ('metadata', models.JSONField(blank=True, help_text='Additional context data (IP, user agent, etc.)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('failed_login', 'Failed Login Attempt'), ('suspicious_ip', 'Suspicious IP Location'), ('multiple_sessions', 'Multiple Active Sessions'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('bulk_data_export', 'Bulk Data Export'), ('data_tampering', 'Data Tampering Detected'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('anomalous_activity', 'Anomalous Activity')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device info from request')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
