# Generated by Django 6.0 on 2025-12-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital Admin'), ('authority', 'Health Authority'), ('superadmin', 'Super Admin')], default='patient', max_length=20),
        ),
    ]
