# Generated by Django 6.0 on 2025-12-30 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('govt_id', models.FileField(blank=True, null=True, upload_to='verification/patient/')),
                ('hospital_license', models.FileField(blank=True, null=True, upload_to='verification/hospital/')),
                ('admin_id_proof', models.FileField(blank=True, null=True, upload_to='verification/hospital/')),
                ('appointment_letter', models.FileField(blank=True, null=True, upload_to='verification/authority/')),
                ('authority_id', models.FileField(blank=True, null=True, upload_to='verification/authority/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
