# Generated by Django 5.2.3 on 2026-02-07 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('complaint_status_updates', models.BooleanField(default=True)),
                ('new_messages', models.BooleanField(default=True)),
                ('authority_responses', models.BooleanField(default=False)),
                ('show_in_feed', models.BooleanField(default=True)),
                ('anonymous_posting', models.BooleanField(default=True)),
                ('show_resolved_publicly', models.BooleanField(default=False)),
                ('hide_profile', models.BooleanField(default=False)),
                ('allow_hospital_contact', models.BooleanField(default=True)),
                ('allow_escalation', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
