# Generated by Django 5.2.3 on 2026-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reactivation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
