# Generated by Django 5.2.3 on 2026-02-09 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='govt_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='govt_id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar'), ('voter_id', 'Voter ID'), ('pan', 'PAN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=255)),
                ('authority_type', models.CharField(choices=[('district', 'District'), ('state', 'State'), ('central', 'Central')], max_length=50)),
                ('department_name', models.CharField(max_length=255)),
                ('jurisdiction_level', models.CharField(max_length=50)),
                ('jurisdiction_state', models.CharField(max_length=100)),
                ('jurisdiction_district', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.TextField()),
                ('official_email', models.EmailField(max_length=254)),
                ('official_phone', models.CharField(max_length=15)),
                ('appointment_letter', models.FileField(upload_to='verification/authority/')),
                ('authority_id_document', models.FileField(upload_to='verification/authority/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_type', models.CharField(choices=[('govt', 'Government'), ('private', 'Private')], max_length=50)),
                ('registration_number', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('license_document', models.FileField(upload_to='verification/hospital/')),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
