# Generated by Django 5.2.3 on 2026-02-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_notification_support_ticket_and_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='accounts.authority'),
        ),
    ]
