# Generated by Django 5.2.3 on 2026-02-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_hospital_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='department_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='authority',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='authority',
            name='official_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
