# Generated by Django 5.2.3 on 2026-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_account_status_user_reactivation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reactivation_evidence',
            field=models.FileField(blank=True, null=True, upload_to='reactivation_appeals/'),
        ),
    ]
