# Generated by Django 5.2.3 on 2026-02-11 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0009_hospital_response_and_complaint_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('patient', 'Patient'), ('hospital', 'Hospital')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_conversations_as_authority', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_conversations', to='complaints.complaint')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_conversations_as_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authorities.authorityconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthoritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time_threshold', models.PositiveIntegerField(default=48, help_text="Hours before a complaint is escalated if hospital hasn't responded")),
                ('view_time_threshold', models.PositiveIntegerField(default=24, help_text="Hours before a complaint is escalated if hospital hasn't viewed it")),
                ('warning_threshold', models.PositiveIntegerField(default=3, help_text='Number of warnings before automatic freeze')),
                ('email_notifications', models.BooleanField(default=True)),
                ('escalation_alerts', models.BooleanField(default=True)),
                ('warning_alerts', models.BooleanField(default=True)),
                ('freeze_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('viewed', 'Viewed by Hospital'), ('responded', 'Responded'), ('resolved', 'Marked Resolved'), ('escalated', 'Escalated to Authority'), ('authority_viewed', 'Viewed by Authority'), ('warning_issued', 'Warning Issued'), ('frozen', 'Hospital Frozen'), ('unfrozen', 'Hospital Reactivated')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='complaints.complaint')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('warning_limit', 'Exceeded warning limit'), ('critical_complaint', 'Critical complaint'), ('non_compliance', 'Non-compliance'), ('investigation', 'Under investigation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('frozen', 'Frozen'), ('pending_review', 'Pending Review'), ('reactivated', 'Reactivated'), ('permanently_blocked', 'Permanently Blocked')], default='frozen', max_length=20)),
                ('explanation_requested', models.BooleanField(default=False)),
                ('explanation_received', models.BooleanField(default=False)),
                ('explanation_text', models.TextField(blank=True, null=True)),
                ('explanation_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('permanently_blocked_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freeze_actions', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('critical', 'Critical'), ('serious', 'Serious'), ('minor', 'Minor')], default='serious', max_length=20)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_warnings', to='complaints.complaint')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_warnings', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('escalation', 'Complaint Escalated'), ('warning', 'Warning Issued'), ('freeze', 'Hospital Frozen'), ('unfreeze', 'Hospital Reactivated'), ('explanation', 'Explanation Received'), ('system', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_notifications', to='complaints.complaint')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_notifications_received', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_notifications', to=settings.AUTH_USER_MODEL)),
                ('freeze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_notifications', to='authorities.hospitalfreeze')),
                ('warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_notifications', to='authorities.hospitalwarning')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
