# Generated by Django 5.2.3 on 2026-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalfreeze',
            name='explanation_evidence',
            field=models.FileField(blank=True, null=True, upload_to='freeze_appeals/'),
        ),
        migrations.AlterField(
            model_name='authoritynotification',
            name='notification_type',
            field=models.CharField(choices=[('escalation', 'Complaint Escalated'), ('new_complaint', 'New Complaint Filed'), ('warning', 'Warning Issued'), ('freeze', 'Hospital Frozen'), ('unfreeze', 'Hospital Reactivated'), ('explanation', 'Explanation Received'), ('system', 'System Alert')], max_length=30),
        ),
    ]
