# Generated by Django 5.2.3 on 2026-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'In Review'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='viewed_by_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='viewed_by_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
