# Generated by Django 5.2.3 on 2026-02-08 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_status_complaint_viewed_by_authority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
