# Generated by Django 5.2.3 on 2026-02-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='unregistered_hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
