# Generated by Django 5.2.3 on 2026-02-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_unregistered_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
