# Generated by Django 5.2.3 on 2026-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_hospital_response_and_complaint_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('service', 'Service Quality'), ('billing', 'Billing'), ('infrastructure', 'Infrastructure'), ('Service Quality', 'Service Quality'), ('Clinical Quality', 'Clinical Quality'), ('Staff Conduct', 'Staff Conduct'), ('Access & Billing', 'Access & Billing'), ('Facility & Safety', 'Facility & Safety'), ('Patient Rights', 'Patient Rights'), ('General', 'General')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'In Review'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='new', max_length=20),
        ),
    ]
